server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yutool_sample?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: sql123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true

# Swagger接口文档配置
api:
  version: v1.0.0
  contactName: yupaits
  contactUrl: https://github.com/yupaits
  contactEmail: ts495606653@hotmail.com
  termsOfServiceUrl:
  license: MIT License
  licenseUrl: https://github.com/yupaits/yutool/blob/master/LICENSE
  title: yutool示例
  description: yutool示例应用
  basePackage: com.yupaits.sample.yutool.jpa
  groups:
    - name: test
      title: 测试分组
      description: 仅供测试
      basePackage: com.yupaits.sample.yutool.jpa.controller
      contactName: yupaits
      contactUrl: https://github.com/yupaits
      contactEmail: ts495606653@hotmail.com